<?php

$objectManager =  \Magento\Framework\App\ObjectManager::getInstance();

$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
$store = $storeManager->getStore();
?>
<?php foreach ($block->getBlogs() as $blog) : ?>
    <a href="JavaScript:Void(0)" data-mage-init='{"redirectUrl": {"event": "click", "url": "<?php echo $store->getBaseUrl(); ?>blog/page/view/id/<?php echo $blog->getId(); ?>"}}' type="button" title="Redirect Button">
        <p><b><?php echo $blog->getTitle(); ?> :</b> </p>
        <p><?php echo $blog->getDescription(); ?></p>
        <hr>
    </a>

<?php endforeach; ?>